import spotipy
from spotipy.oauth2 import SpotifyOAuth
import random
auth_manager = SpotifyOAuth(client_id="enter client_id",
                            client_secret="enter client_secret",
                            redirect_uri="http://google.com/",
                            scope="user-library-read user-top-read playlist-modify-public")
class SpotifyBot:
    def __init__(self):
        self.spotify = spotipy.Spotify(auth_manager=auth_manager)
        self.user_id = '31ojsle5q4bh3bewzlqqy32xazuu'
    def top_artists_id(self):
        top_artists = self.spotify.current_user_top_artists(limit=20)
        artists_ids = []
        for artists in top_artists["items"]:
            artists_ids.append(artists['id'])
        return artists_ids
    def pull_songs(self, artist_list):
        final_song_list = []
        for artists_id in artist_list:
            top_songs = self.spotify.artist_top_tracks(artists_id, "US")
            for songs in top_songs["tracks"]:
                random_select = random.getrandbits(1)
                if random_select == 0:
                    final_song_list.append(songs["id"])
        return final_song_list
    def create_favorite_artists(self):
        artist_list = self.top_artists_id()
        song_list = self.pull_songs(artist_list)
        playlist_name = "Top Artists Playlist (Python)"
        while len(song_list) >= 100:
            song_list.pop()
        self.create_playlist(song_list, playlist_name)
    def create_related_artists(self):
        the_smiths = self.spotify.artist_related_artists("3yY2gUcIsjMr8hjo51PoJ8")
        related_artists = []
        for artist in the_smiths['artists']:
            related_artists.append(artist['id'])
        related_songs = self.pull_songs(related_artists)
        while len(related_songs) >= 100:
            related_songs.pop()
        playlist_name = "Related Artists Playlist (Python)"
        self.create_playlist(related_songs, playlist_name)
    def create_playlist(self, songData, playlistName):
        playlist = self.spotify.user_playlist_create(self.user_id, playlistName, public=True, collaborative=False, description='Playlist generated by python and spotipy api')
        self.spotify.playlist_add_items(playlist['id'], songData, position=None)
spotify_bot = SpotifyBot()
spotify_bot.create_favorite_artists()
spotify_bot.create_related_artists()
